# config/packages/security.yaml

security:
    encoders:
        App\Entity\Admin:
            algorithm: bcrypt

    providers:
        admin_provider:
            entity:
                class: App\Entity\Admin
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\AdminAuthenticator
            logout:
                path: app_logout
                target: app_home

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
